version: '3.8'

services:
  app:
    build: .
    container_name: shreeeyan-shopping-mart-app
    ports:
      - "8080:8080"
    depends_on:
      - nexus
      - sonarqube

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  nexus-data:
